---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "{{ play_name | default('Install Docker') }}"
    serial: "{{ serial_count | default('100%') }}"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    roles:
      - role: packages-docker
        when: allow_package_installation|bool == true
      - role: docker-storage
      - role: docker-proxy
        when: >
                (https_proxy is defined and https_proxy is not empty) or
                (http_proxy is defined and http_proxy is not empty) or
                (no_proxy is defined and no_proxy is not empty)
      - role: docker
