---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "{{ play_name | default('Start Kubernetes Proxy') }}"
    serial: "{{ serial_count | default('100%') }}"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    pre_tasks:
      - name: stop kube-proxy service
        service:
          name: kube-proxy.service
          state: stopped
          enabled: no
        ignore_errors: yes
        when: upgrading is defined and upgrading|bool == true

    roles:
      - kube-proxy
